---
title: "01 — Map of Studies"
subtitle: "Salmonella AMR in Africa: A review"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    highlight: tango
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.width = 10, fig.height = 8)
knitr::opts_knit$set(root.dir = "/Users/hitelab/Desktop/2026_AMR_Review/01_Data")
```

## Overview

This script plots a map of Africa showing the number of studies included in the analysis (Figure 1b).

---

```{r map-of-studies}
###This scrip is used to plot map of Africa showing the 
#number of studies included in the analysis (Figure 1b)#######
###loading packages
library(tidyverse)
library(tmap)
library(leaflet) 
library(sf) 
library(RColorBrewer)
library(htmltools) 
library(leafsync) 
library(kableExtra) 
library(rnaturalearth)
library(viridis)
library(mapview)
sf_use_s2(FALSE)
#> Spherical geometry (s2) switched off
##loading data
AMR_clean <- read.csv("AMR_clean.csv")
world <- ne_countries(type = 'countries', 
                      scale = 'small', 
                      returnclass = "sf") 
###using map view package to plot world AMR rates
# AMR <- AMR %>%
#   na.omit
df <- AMR_clean %>%
  group_by(country) %>%
  select(country, percent_resistant, x_coordinate, y_coordinate, species) %>%
  set_names(c("country", "percentage_resistance", "long", "lat", "species")) %>%
  filter(!is.na(percentage_resistance)) 
df %>%
  count(country)%>%   
  view()
###changing percentage_resistance to numeric class
df$percentage_resistance <- as.numeric(as.character(df$percentage_resistance))
##Summarizing the data
df1 <- df %>%
  group_by(country) 
  # summarise(percentage_resistance = mean(percentage_resistance, na.rm = TRUE))
world_amr1 <- world %>%
  filter(continent == "Africa") %>%
  select(country = geounit,iso_a3, geometry) #%>%
 # left_join(df1, by = "country")
##Adding number of studies to the dataset
data1 <- AMR_clean %>% 
  group_by(country, author) %>% 
  filter(row_number()==1) %>% 
  dplyr:: select(country) %>%
  distinct() %>% as.data.frame() # drop duplicates.

data2 <- data1 %>% 
  group_by( country) %>% 
  mutate(no_studies = n()) %>%
  dplyr:: select(country, no_studies) %>%
  distinct() %>% as.data.frame() # drop duplicates.

#Joining the data to add number of studies
world_amr2 <- world_amr1 %>%
  left_join(data2, by = "country")%>%
  unique()
# world_amr2 %>%
#   mapview(zcol = "no_studies",
#           col.regions = viridisLite::plasma) 
tmap_mode("plot")
# plotting the map
africa_map<-tm_shape(world_amr2) + 
  tm_polygons(col = "no_studies",  
              title = "number of studies",
              palette = "okabe") +
  tm_text("iso_a3", size = 0.7) +
  tm_layout(legend.position = c("left", "bottom"))
africa_map
tmap_save(africa_map, filename = "africamap.png", dpi = 300)
library(tmap)
tmap_mode("view")
map <- tm_shape(world_amr2) +
  tm_polygons(col = "no_studies",
              n = 1,
              palette = "Blues") +
  tm_text("iso_a3")  # Add country names
map <- map + tm_shape(world_amr2) +
  tm_text("no_studies", size = "no_studies", root = 2)+
  tm_text("iso_a3", size =5)# Add number of studies
tryCatch(print(map), error = function(e) {
  message("Interactive map could not render (leaflegend version conflict): ", e$message)
  message("The static map (africamap.png) was saved successfully.")
})


############################################
#########################
```

---


